import { ProjectType } from "@/types/project";

const ProjectList: ProjectType[] = [
  {
    city: "Bangalore",
    project: "Ajmera Lake side Paradise",
    location: "Yelahanka",
    type: "Apartments",
    units: "160 units",
    totalLand: "10 Acres",
    sizes:
      "-> 1 bed Prime residence 666 sq. ft. at ₹45 Lakhs onwards* <br/>-> 2 bed Grand residence 1008 sq. ft. at ₹77 lakhs onwards*<br/>-> 2 bed Luxe residence 1170 sq. ft. at ₹87 Lakhs onwards*",
    image: "ajmera_lakeside_paradise-yelahanka-bengaluru-ajmera_group.avif",
    home_screen: "no",
  },
  {
    city: "Bangalore",
    project: "Assetz marq",
    location: "Kannamangala , Whitefield",
    type: "Apartments",
    units: "1700 units",
    totalLand: "22 Acres",
    sizes:
      "3 BHK 2T - size - 1377Sqft Price - 1.47 Cr                                                                                                                                                3BHK 3T- Size - 1630Sqft Price - 1.73 Cr                                                                                                                                                             3BHK 3T - 1937Sqft Price -2.03 Cr                                                                                                                                                                      4BHK 4T - 2275Sqft Price - 2.38 Cr",
    image: "Assetz 63 degree East.jpg",
    home_screen: "no",
  },
  {
    city: "Bangalore",
    project: "Birla Alokya",
    location: "Soukya Road, Whitefield, Bengaluru",
    type: "",
    units: "",
    totalLand: "7.9 Acres",
    sizes: "3BHK Duplex Homes starting from 2.1Cr",
    image: "Birla Alokya.jpg",
    home_screen: "no",
  },
  {
    city: "Bangalore",
    project: "Birla Trimaya",
    location: "Shettigere road",
    type: "Apartments",
    units: "480 Units",
    totalLand: "54 Acres",
    sizes:
      "1,2,3BHK 3t PWD ,  Area - 559sqft - 1213sqft , Duplex villament - 4BHK + maid room  Area - 2175, Row houses - 4BHK + maid +PWD ,  Area - 2516 Price - 3Cr Onwards",
    image: "Birla-Trimaya-main.webp",
    home_screen: "no",
  },
  {
    city: "Bangalore",
    project: "Godrej lakeside Orchards",
    location: "Sarjapur Main Road",
    type: "Apartments",
    units: "900+",
    totalLand: "15 Acres",
    sizes:
      "2 BHK 2T : 1200 -1270 Sft -- 1.38 Cr<br/>3 BHK 2T: 1500 -1600 Sft --1.73 Cr<br/>3 BHK 3T: 1750-1980 Sft -- 2.1 Cr<br/>3.5 BHK 3T: 2150 -2250 Sft  --2.48 Cr                                                                                                                                    4 BHK 4T: 2600 -2700 Sft  --3 Cr                                                                                                                                           Price : Per Sqft - 11500",
    image: "Godrej Lakeside Orcide.jfif",
    home_screen: "yes",
  },
  {
    city: "Bangalore",
    project: "GoyalCo Orchid Salisbury",
    location: "Prestige Somerville",
    type: "Apartments",
    units: 600,
    totalLand: "6+ Acres",
    sizes:
      "2 BHK - Compact: 900-1000 Sft<br/>Rs. 85 Lacs Onwards<br/>2 BHK - Regular: 1100-1200 Sft<br/>Rs. 1.05 Cr Onwards<br/>3 BHK + 2T: 1400-1500 Sft<br/>Rs. 1.35 Cr Onwards<br/>3 BHK + 3T: 1600-1700 Sft<br/>Rs. 1.53 Cr Onwards",
    image: "Goyal - Co -Salisbury.jpg",
    home_screen: "no",
  },
  {
    city: "Bangalore",
    project: "Kalyani Living Tree",
    location: "KIADB Tech park (Baglur)",
    type: "Apartments",
    units: "2522 units",
    totalLand: "25 Acres",
    sizes:
      "1 BHK        576 Sq.ft.                ₹ 47.23 Lakhs*        <br/>2 BHK        1041 Sq.ft.        ₹ 85.36 Lakhs*        <br/>2.5 BHK        1143 Sq.ft.        ₹ 93.73 Lakhs*        <br/>3 BHK        1316 Sq.ft.        ₹ 1.07 Cr*        <br/>3 BHK        1639 Sq.ft.        ₹ 1.34Cr*        <br/>3 BHK        1927 Sq.ft.        ₹ 1.58 Cr*                                                    Per Sqft - 8200 All Inclusive + Registration",
    image: "Kalyani-arcadia-bangalore.jpg",
    home_screen: "no",
  },
  {
    city: "Bangalore",
    project: "Lodha Azur",
    location: "Begur Road",
    type: "Apartments",
    units: "500 units",
    totalLand: "10.7 Acres",
    sizes:
      "3bhk - 1960 sft - super built up area - 2.4cr onwards<br/><br/><br/>3.5 bhk - 2300 sft - super built up area - 3.10 cr onwards<br/><br/>4bhk - 3000 sft - super built up area - 3.7 cr onwards",
    image: "Lodha Azure.jpeg",
    home_screen: "no",
  },
  {
    city: "Bangalore",
    project: "Nikoo homes",
    location: "Bharathicity",
    type: "Apartments",
    units: "568 Units",
    totalLand: "",
    sizes:
      "2,2.5,3,3.5 BHK , Area - 1144 sqft -1872 sqft , Price : 1.25 Cr to 2.10 Cr",
    image: "Nikoo Homes.jfif",
    home_screen: "no",
  },
  {
    city: "Bangalore",
    project: "Prestige Camden Gardens",
    location: "Thanisandara Road",
    type: "Apartments",
    units: 120,
    totalLand: "2 Acres",
    sizes:
      "3 BHK: 1600-1900 Sft<br/>Rs. 1.85 Cr Onwards<br/>3.5 BHK: 2000-2200 Sft<br/>Rs. 2.35 Cr Onwards<br/>4.5 BHK: 2700+ Sft<br/>Rs. 3.20 Cr Onwards",
    image: "prestige-camden-gardens.webp",
    home_screen: "no",
  },
  {
    city: "Bangalore",
    project: "Prestige Glen Brook",
    location: "Borewell Road, Whitefield",
    type: "Apartments",
    units: 285,
    totalLand: "4.5 Acres",
    sizes:
      "3 BHK 2T: 1486-1647 Sft<br/> Rs. 1.93 Cr Onwards<br/> 3 BHK 3T: 1810-2057 Sft<br/> Rs. 2.35 Cr Onwards<br/> 4 BHK 4T: 2928 Sft<br/> Rs. 3.80 Cr Onwards",
    image: "Prestige Glenbrook.jfif",
    home_screen: "no",
  },
  {
    city: "Bangalore",
    project: "Prestige Kings County",
    location: "Jigani, Near Ecity",
    type: "Plots",
    units: 700,
    totalLand: "70 Acres",
    sizes: "Plot Sizes: 1500 / 1800 / 2400 Sft & Bigger Sizes",
    image: "Prestige Kings County.jpg",
    home_screen: "no",
  },
  {
    city: "Bangalore",
    project: "PRESTIGE PINE FOREST",
    location: "ECC road , Whitefield",
    type: "Apartments",
    units: "250 Units",
    totalLand: "9.5 Acres",
    sizes:
      "Luxurious 3 & 4 BHK Apartments                                                                     sizes : 2750 - 3600Sft                                                                                    Base Price : 12456 per Sq ft.",
    image: "Prestige-Pine Forest Whitefield.jpg",
    home_screen: "yes",
  },
  {
    city: "Bangalore",
    project: "Prestige Raintree Park",
    location: "Whitefield - Varthur Road",
    type: "Apartments",
    units: 1368,
    totalLand: "28 Acres (Phase 1)",
    sizes:
      "✅ 3 BHK: 2005-2020 Sft - Rs. 2.9 Cr Onwards<br/>✅ 3 BHK + Maid's Room: 2187-2400 Sft - Rs. 3.2 Cr Onwards<br/>✅ 3 BHK + Study + Maid's Room: 2451-2588 Sft - Rs. 3.5 Cr Onwards<br/>✅ 4 BHK + Maid's Room: 2900-2956 Sft - Rs. 4 Cr Onwards<br/>✅ 5 BHK (4 BHK + Maid's Room + Studio): 3500-3700 Sft - Rs. 5 Cr Onwards",
    image: "Prestige-Raintree-Park.jpg",
    home_screen: "yes",
  },
  {
    city: "Bangalore",
    project: "Prestige Somerville",
    location: "Whitefield - Marathalli Road",
    type: "Apartments",
    units: 306,
    totalLand: "6.5 Acres",
    sizes:
      "3 BHK 3T: 1773-1818 Sft<br/> Rs. 2.6 Cr Onwards<br/> 3 BHK 3T + Study: 1962 Sft<br/> Rs. 2.9 Cr Onwards<br/> 4 BHK 5T + Maid's Room: 2616 Sft<br/> Rs. 3.9 Cr Onwards",
    image: "Prestige Somerville.jpg",
    home_screen: "yes",
  },
  {
    city: "Bangalore",
    project: "Prestige White Meadows",
    location: "Whitefield main road",
    type: "Apartments",
    units: "398 Units",
    totalLand: "28.5 Acres",
    sizes: "4BHK - 4000sft to 4300sqft price :  6.25Cr",
    image: "Prestige white Meadows.jfif",
    home_screen: "yes",
  },
  {
    city: "Bangalore",
    project: "Shriram pristine Estates",
    location: "Doddabellapur ( Next to Dmart & on State Highway )",
    type: "",
    units: "Plots - 513",
    totalLand: 49,
    sizes: "",
    image: "Shriram pristine Estates.jpg",
    home_screen: "no",
  },
  {
    city: "Bangalore",
    project: "SNN Raj High Gardens",
    location: "Near Chandapura, Electronic City",
    type: "Apartments",
    units: "802 Units",
    totalLand: "9.12 acres",
    sizes: "2bhk - 880-1120 sft<br/>3 bhk - 1480-1685 sft",
    image: "SNN Raj High Gardens.jpg",
    home_screen: "no",
  },
  {
    city: "Bangalore",
    project: "Sumadhura Epitome",
    location: "Rachnahalli Main Road, Behind Manayata Tech Park",
    type: "",
    units: 262,
    totalLand: 1.8,
    sizes:
      "2bhk-1270sft - 49 units<br/><br/>2.5bhk: 1545 to 1610sft - 90 units<br/><br/>3bhk: 1670 to 1830sft-101 units.<br/><br/>3.5bhk: 2075sft-22 units.",
    image: "Sumadhura Epitome.jfif",
    home_screen: "no",
  },
  {
    city: "Hyderabad",
    project: "The Prestige City",
    location: "Rajendra Nagar",
    type: "Apartments",
    units: 4647,
    totalLand: "64 Acres",
    sizes: "2,3 & 4 BHK 1631 SFT TO 3355 SFT",
    image: "The Prestige City.jpg",
    home_screen: "no",
  },
  {
    city: "Hyderabad",
    project: "Vaishnaoi Southwoods Villas",
    location: "Shamshabad",
    type: "villa",
    units: 260,
    totalLand: "44 Acres",
    sizes:
      "luxurious villa sizes 328 to 500 square yard                                                                                                                               price 5cr to 10 cr",
    image: "Vaishnaoi Southwoods Villa.jpg",
    home_screen: "no",
  },
  {
    city: "Hyderabad",
    project: "Prestige Clairmont",
    location: "Kokapet",
    type: "Apartments",
    units: 938,
    totalLand: "7.5 Acres",
    sizes:
      "flat 3 bhk & 4 bhk  apartment sizes                                                                                                                                              3 bhk :1989 to 2944.sft 4 BHK 4060 sft price  2.8cr to 4.24 cr",
    image: "Prestige-Clairemont.jpg",
    home_screen: "no",
  },
  {
    city: "Hyderabad",
    project: "Asbl Loft",
    location: "Financial District",
    type: "apartments",
    units: "",
    totalLand: "5 Acres",
    sizes:
      "flat 3 bhk only apartment sizes 1695 to 1870 sqft price 1.9 cr to 2.5 cr onwards",
    image: "Hyderabad_ASBL Loft.jpg",
    home_screen: "no",
  },
  {
    city: "Hyderabad",
    project: "ASBL Spectra",
    location: "Financial District",
    type: "Apartments",
    units: "",
    totalLand: "7.85 Acres",
    sizes: "flat 3 bhk only apartment sizes 1980 to 2220 SFT",
    image: "",
    home_screen: "no",
  },
  {
    city: "Hyderabad",
    project: "Sattva Lake Ridge",
    location: "Kokapet",
    type: "apartments",
    units: 897,
    totalLand: "9.5 Acres",
    sizes: "3/ 4 /5 bhk flat size 2152- 5472 sqft price 2.6 to 7.5 cr",
    image: "Sattva-Lake-Ridge.jpg",
    home_screen: "no",
  },
  {
    city: "Hyderabad",
    project: "The Pearl by Auto Realty",
    location: "Hitec City",
    type: "apartments",
    units: "",
    totalLand: "7.54 Acres",
    sizes: "luxurious 4 bhk apartment 5300-5400 sqft price 8.48-8.64 cr",
    image: "The Pearl by Auto Realty.jpg",
    home_screen: "no",
  },
  {
    city: "Hyderabad",
    project: "Prestige Rainbow Waters",
    location: "Rai Durg",
    type: "apartments",
    units: 150,
    totalLand: "3 Acres",
    sizes: "luxurious 4 & 5 BHK sizes : 4955-8001  price 5.45 cr 8.8 cr",
    image: "prestige-vaishnaoi-rainbow-waters.jpeg",
    home_screen: "no",
  },
  {
    city: "Hyderabad",
    project: "Prestige Spring Heights",
    location: "Budwel",
    type: "Apartments",
    units: 1656,
    totalLand: "11 Acres",
    sizes: "3 & 4 BHK 1576SFT to 3051 SFT",
    image: "Prestige Spring Heights.webp",
    home_screen: "no",
  },
  {
    city: "Noida",
    project: "Apex Quebec",
    location: "wave city ghaziabad .",
    type: "Apartments",
    units: 701,
    totalLand: "4.88 acers",
    sizes:
      "2 BHK (950 SFT): RS .85.5 lakhs Onwords:  3BHK (1680SFT);Rs 1.51 Cr .( 1960 SFT) Rs 1.76 Cr , (2070 SFT) Rs . 1.86 cr . 4BHK + servent ( 2400 sft ) : Rs . 2.16 Cr ,  4BHK + servent + terrace .( 2510 SFT ) : Rs 2.25 Cr",
    image: "Apex-quebec.jpeg",
    home_screen: "no",
  },
  {
    city: "Noida",
    project: "Apex D Rio",
    location: "Ahinsa khand 2. Ghaziabad",
    type: "Apartments",
    units: 701,
    totalLand: "3.45 acers",
    sizes:
      "3 BHK (2190 SFT ) Rs . 2.74 Cr. 3 BHK ( 2460 SFT ) Rs . 3.08 Cr . 4 BHK ( 3095 SFT ): Rs . 4.49 Cr . 4BHK ( 3695 SFT ) : Rs 5.36 Cr .",
    image: "Apex Drio.jpg",
    home_screen: "no",
  },
  {
    city: "Noida",
    project: "T and T The Blue",
    location: "Siddhartha vihar, Ghaziabad",
    type: "Apartments",
    units: 293,
    totalLand: "4 Acers",
    sizes: "3 BHK ( 2024 SFT) Rs .1.92 Cr , 3 BHK (2048 SFT .) : Rs 1.94 Cr .",
    image: "T & T The-Blue.jpg",
    home_screen: "no",
  },
  {
    city: "Noida",
    project: "T and T Digitown",
    location: "Siddhartha vihar, Ghaziabad",
    type: "Apartments",
    units: 103,
    totalLand: "4 Acers",
    sizes:
      "3 BHK Apartments<br/>Carpet Area: 831.41 - 1294.27 sq.ft. (77.24 - 120.24 sq.m.) Rs , 1.36 cr to 2.1 Cr .",
    image: "T&T Digitown.jpg",
    home_screen: "no",
  },
  {
    city: "Noida",
    project: "T and T Eutopia",
    location: "Siddhartha vihar, Ghaziabad",
    type: "Apartments",
    units: 257,
    totalLand: "8 Acers",
    sizes:
      "3 BHK Apartments:<br/>Carpet Area: 1120 - 1259.82 sq.ft. (104.05 - 117.04 sq.m.)  Rs . 1.97Cr to 2.15 Cr . 4 BHK Apartments:<br/>Carpet Area: 1337 - 1801.83 sq.ft. (124.21 - 167.4 sq.m.) Rs . 2.16Cr  to 2.99 Cr",
    image: "T and T Eutopia.jpg",
    home_screen: "no",
  },
  {
    city: "Noida",
    project: "AU The Sunflower",
    location: "Shahpur Bamheta, NH - 24 Ghaziabad, Ghaziabad",
    type: "Apartments",
    units: 720,
    totalLand: "9 Acers",
    sizes:
      "3BHK  ( 2975 SFT ) : Rs 2.82 Cr . 3BHK ( 3822 SFT ) : Rs 3.63 Cr . 3 BHK( 4000 SFT ) : Rs . 3.80 Cr",
    image: "ausunflower.jpg",
    home_screen: "no",
  },
  {
    city: "Noida",
    project: "Saya Gold Homes",
    location: "Vaibhav Khand, Indirapuram, Ghaziabad, Uttar",
    type: "Apartments",
    units: 428,
    totalLand: "5 Acers",
    sizes:
      "2 BHK Apartments:<br/>Super Built-up Area: (1080 - 1770 sq.ft.) Rs . 89 lakhs to 1.17 Cr  3 BHK Apartments:<br/>Carpet Area:( 853 - 1795 sq.ft. ) Rs . 1.39 Cr to 2. 92 Cr . 4 BHK Apartments:<br/>Super Built-up Area:( 2370 - 2470 sq.ft. ) Rs . 2.26 cr to 2.96 Cr .",
    image: "Saya gold homes.jpg",
    home_screen: "no",
  },
  {
    city: "Noida",
    project: "Prateek Grand City",
    location: "Siddhartha vihar, Ghaziabad",
    type: "Apartments",
    units: 1520,
    totalLand: "40 Acers",
    sizes:
      "2 BHK Apartments: Super Built-up Area: (770 - 1155 sq.ft.) Rs . 51 lakhs to 92.4 lakhs . 3 BHK Apartments:<br/>Super Built-up Area:  (1380 - 1795 sq.ft.) Rs . 1.1 cr to 1.53 Cr .",
    image: "Prateek Grand City.jpg",
    home_screen: "no",
  },
];

export default ProjectList;
